# docker-compose.yml
version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: "python run.py"
    volumes:
      - .:/app
    restart: always
    ports:
      - "4000:8080"
    networks:
      - mynet

networks:
  mynet:
    external: true
    name: mongo_connection
