# docker-compose.yml
version: "3.9"

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    networks:
      - mynet

  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: "python run.py"
    volumes:
      - .:/app
    restart: always
    ports:
      - "4000:8080"
    networks:
      - mynet
    depends_on:
      - mongo

networks:
  mynet:
